module.exports = {
	democracy_list: require('./democracy/list'),
	democracy_read: require('./democracy/read'),
	proposal_list_public: require('./proposal/list_public'),
	proposal_read_public: require('./proposal/read_public'),
	ballot_list_public: require('./ballot/list_public'),
	membership_list: require('./membership/list'),
	membership_create: require('./membership/create'),
	membership_read: require('./membership/read'),
	membership_delete: require('./membership/delete'),
	proposal_list: require('./proposal/list'),
	proposal_create: require('./proposal/create'),
	proposal_read: require('./proposal/read'),
	proposal_delete: require('./proposal/delete'),
	ballot_list: require('./ballot/list'),
	ballot_create: require('./ballot/create'),
	ballot_read: require('./ballot/read'),
	ballot_update: require('./ballot/update'),
	ballot_delete: require('./ballot/delete')
}
