CREATE TABLE profile( LIKE base INCLUDING ALL );

ALTER TABLE profile ADD COLUMN auth_zkpp VARCHAR NOT NULL;
ALTER TABLE profile ADD COLUMN auth_salt VARCHAR NOT NULL;
ALTER TABLE profile ADD COLUMN auth_public VARCHAR;
ALTER TABLE profile ADD COLUMN auth_private VARCHAR;
ALTER TABLE profile ADD COLUMN auth_token VARCHAR;
ALTER TABLE profile ADD COLUMN auth_expiry TIMESTAMP;

CREATE TRIGGER profile_update BEFORE UPDATE ON profile FOR EACH ROW EXECUTE PROCEDURE date_updated();

