CREATE TYPE BUCKETS AS ENUM ('signup', 'profile');

CREATE TABLE token( LIKE base INCLUDING ALL );

ALTER TABLE token ADD COLUMN token VARCHAR UNIQUE NOT NULL;
ALTER TABLE token ADD COLUMN bucket BUCKETS NOT NULL;

CREATE TRIGGER token_update BEFORE UPDATE ON token FOR EACH ROW EXECUTE PROCEDURE date_updated();
