CREATE TYPE BUCKETS AS ENUM ('email', 'signup', 'account', 'profile');

CREATE TABLE token( LIKE base INCLUDING ALL );

ALTER TABLE token ADD COLUMN token VARCHAR UNIQUE NOT NULL DEFAULT md5(random()::text);
ALTER TABLE token ADD COLUMN bucket BUCKETS NOT NULL;
ALTER TABLE token ADD COLUMN zkpp VARCHAR DEFAULT NULL;
ALTER TABLE token ADD COLUMN salt VARCHAR DEFAULT NULL;

CREATE TRIGGER token_update BEFORE UPDATE ON token FOR EACH ROW EXECUTE PROCEDURE date_updated();

