CREATE TABLE auth( LIKE base INCLUDING ALL );

ALTER TABLE auth ADD COLUMN token_id VARCHAR;
ALTER TABLE auth ADD COLUMN pke_public VARCHAR;
ALTER TABLE auth ADD COLUMN pke_private VARCHAR;
ALTER TABLE auth ADD COLUMN pke_secret VARCHAR;
ALTER TABLE auth ADD COLUMN pake_public VARCHAR;
ALTER TABLE auth ADD COLUMN pake_private VARCHAR;

CREATE TRIGGER auth_update BEFORE UPDATE ON auth FOR EACH ROW EXECUTE PROCEDURE date_updated();

